/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Json = ColumnType<JsonValue, string, string>;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export interface Account {
  access_token: string | null;
  access_token_expires_at: Date | null;
  account_id: string;
  created_at: Generated<Date>;
  id: Generated<number>;
  id_token: string | null;
  password: string | null;
  provider_id: string;
  refresh_token: string | null;
  refresh_token_expires_at: Date | null;
  scope: string | null;
  updated_at: Date;
  user_id: number;
}

export interface Project {
  auto_deployment: Generated<number>;
  coding_agent_type: string;
  description: string;
  error_message: string | null;
  github_owner: string;
  github_repo: string;
  id: Generated<number>;
  name: string;
  status: string;
  tidbcloud_cluster_id: string;
  tidbcloud_connection_url: string;
  user_id: number;
  vercel_project_id: string;
  vercel_team_id: string;
  vercel_team_token: string;
}

export interface Session {
  created_at: Generated<Date>;
  expires_at: Date;
  id: Generated<number>;
  ip_address: string | null;
  token: string;
  updated_at: Date;
  user_agent: string | null;
  user_id: number;
}

export interface SystemSettings {
  key: string;
  value: Json;
}

export interface Task {
  git_branch_name: string;
  git_revision_ref: string;
  id: Generated<number>;
  name: string;
  parent_task_id: number | null;
  parent_task_revision_ordinal: number | null;
  project_id: number;
  user_id: number;
}

export interface TaskRevision {
  agent_message: Json | null;
  agent_result: string | null;
  created_at: Date;
  error: string | null;
  git_commit_sha: string | null;
  id: Generated<number>;
  ordinal: number;
  project_id: number;
  prompt: string;
  sandbox_type: string;
  started_at: Date | null;
  status: string;
  stopped_at: Date | null;
  task_id: number;
  tidbcloud_branch_id: string | null;
  user_id: number;
  user_prompt: string;
  vercel_deployment_error: string | null;
  vercel_deployment_id: string | null;
  vercel_deployment_status: string | null;
  vercel_sandbox_id: string | null;
}

export interface TidbcloudBranch {
  cluster_id: string;
  connection_url: string | null;
  created_at: Date;
  id: string;
  name: string;
  parent_id: string | null;
  status: string;
}

export interface UiSession {
  created_at: Date;
  id: Generated<number>;
  logs: Json;
  message: Json | null;
  project_id: number | null;
  slug: string;
  task_id: number | null;
  title: string;
  updated_at: Date;
  user_id: number;
}

export interface User {
  avatar_url: string;
  created_at: Generated<Date>;
  email: string;
  email_verified: number;
  id: Generated<number>;
  name: string;
  role: Generated<string>;
  updated_at: Generated<Date>;
}

export interface UserSetting {
  default_vercel_project_team_id: string | null;
  github_login: string | null;
  github_token: string | null;
  openai_api_key: string | null;
  tidbcloud_organization_id: string | null;
  tidbcloud_private_key: string | null;
  tidbcloud_project_id: string | null;
  tidbcloud_public_key: string | null;
  user_id: number;
  vercel_blob_storage_id: string | null;
  vercel_blob_storage_rw_token: string | null;
  vercel_blob_team_id: string | null;
  vercel_token: string | null;
}

export interface VercelSandbox {
  created_at: Date;
  id: string;
  status: string;
  stopped_at: Date | null;
  type: string;
  updated_at: Date;
  user_id: number;
}

export interface Verification {
  created_at: Generated<Date>;
  expires_at: Date;
  id: Generated<number>;
  identifier: string;
  updated_at: Generated<Date>;
  value: string;
}

export interface DB {
  account: Account;
  project: Project;
  session: Session;
  system_settings: SystemSettings;
  task: Task;
  task_revision: TaskRevision;
  tidbcloud_branch: TidbcloudBranch;
  ui_session: UiSession;
  user: User;
  user_setting: UserSetting;
  vercel_sandbox: VercelSandbox;
  verification: Verification;
}
